"""Price observation daily postgres uuid

Revision ID: 1ee8a2394d07
Revises: 506d60f4f70d
Create Date: 2026-06-08 19:08:14.856654

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ee8a2394d07'
down_revision = '506d60f4f70d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('priceobservationdaily', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    op.alter_column('productalias', 'first_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('productalias', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productalias', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('productalias', 'first_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('priceobservationdaily', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
