"""Add price observations daily

Revision ID: 506d60f4f70d
Revises: 6e1bfbf19fde
Create Date: 2026-06-08 18:40:41.586499

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '506d60f4f70d'
down_revision = '6e1bfbf19fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priceobservationdaily',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('retailer_id', sa.Uuid(), nullable=False),
    sa.Column('observed_date', sa.Date(), nullable=False),
    sa.Column('price_eur_min', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_eur_max', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_eur_avg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_special_sale', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'retailer_id', 'observed_date', name='uq_price_observation_daily')
    )
    op.create_index(op.f('ix_priceobservationdaily_observed_date'), 'priceobservationdaily', ['observed_date'], unique=False)
    op.create_index(op.f('ix_priceobservationdaily_product_id'), 'priceobservationdaily', ['product_id'], unique=False)
    op.create_index(op.f('ix_priceobservationdaily_retailer_id'), 'priceobservationdaily', ['retailer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_priceobservationdaily_retailer_id'), table_name='priceobservationdaily')
    op.drop_index(op.f('ix_priceobservationdaily_product_id'), table_name='priceobservationdaily')
    op.drop_index(op.f('ix_priceobservationdaily_observed_date'), table_name='priceobservationdaily')
    op.drop_table('priceobservationdaily')
    # ### end Alembic commands ###
