"""Not null price in price observation

Revision ID: 6e1bfbf19fde
Revises: 103bb4712995
Create Date: 2026-06-08 17:22:41.834646

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6e1bfbf19fde'
down_revision = '103bb4712995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM priceobservation WHERE price_eur IS NULL")
    op.alter_column('priceobservation', 'price_eur',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('priceobservation', 'price_eur',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###
